### ISSUE TITLE
Missing idl file in target

### ISSUE THREAD

**Issue by BunnyNomics101** [ali-bahjati/balex#1]
Tried to deploy and it throws this error:

thread 'main' panicked at 'Code not parseable: Error("bump targets should not be provided with init. Please use bump without a target.")', lang/syn/src/idl/file.rs:353:58

How to circumvent this error?

**Comment by ali-behjati** [comment]
Did you try to run `anchor build` before? Apparently anchor won't generate idl files when you run `anchor deploy`

**Comment by BunnyNomics101** [comment]
Yes, thank you!
